### ISSUE TITLE
Introduce reactjs boilterplate

### ISSUE THREAD

**Issue by kahneraja** [DevProgress/csv-simple-search#1]
Yes yes!!! Boilerplait reactjs with vanialla layout for later styling!

**Comment by alexyaseen** [comment]
I'm on it

**Comment by alexyaseen** [comment]
Open question as to how we want to handle CSS. There are a few options:
1.  Regular stylesheet via `<link>`
2. Webpack can transform require('styles.css') into a regular stylesheet via `<link>`
3. Webpack CSS Modules https://github.com/css-modules/webpack-demo
4. CSS in JS https://github.com/FormidableLabs/radium

**Comment by kahneraja** [comment]
i'm not sure @alexyaseen 

is one approach easier and simpler from a UX perspective - so we can get more people onboard quickly?

**Comment by alexyaseen** [comment]
2 might be the best compromise for now to keep the most people involved but still get autoprefixer benefits

**Comment by kahneraja** [comment]
Update README when done so others know how to fire up their local :)
