### ISSUE TITLE
On page load get csv file name from querystring

### ISSUE THREAD

**Issue by kahneraja** [DevProgress/csv-simple-search#17]
app.com/csv/file1
app.com/csv/file2
app.com/csv/abc...

When loaded retrieves csv file "file1.csv" and renders page.

If no route is provided (app.com) use "default.csv".

**Comment by kahneraja** [comment]
Needs to pick up csv data changes on page reload.

**Comment by decause** [comment]
The "if no route is provided use 'default.csv'." part seems legit. In the case there were other .csv files there, that could be useful. I would imagine most users only ever needing the default route, and maybe this can be a way for the "admin" to check a new csv before making it the default?

Other comments?

**Comment by kahneraja** [comment]
let’s do it based on the param maybe?, i don’t think we can rely on routing.
app.com?file=abc.csv
@samuelcole
