### ISSUE TITLE
Confirm deploy/hosting strategy

### ISSUE THREAD

**Issue by decause** [DevProgress/csv-simple-search#19]
The result of <code>npm run build</code> will need to be deployed somewhere and then linked to on the intranet. Must discuss with Ops team.

**Comment by samuelcole** [comment]
i'll help on our end, i'm hoping to generate a pretty tidy `index.html` and maybe a `package.js` but that should be it

**Comment by samuelcole** [comment]
(and then they can add `default.csv`, before they upload it)

**Comment by decause** [comment]
SGTM :+1:

**Comment by alexyaseen** [comment]
fonts are now automatically getting moved to /dist, they'll need to be there too

**Comment by alexyaseen** [comment]
If we're going to use gh-pages, it should be quite easy. I'm happy to get that working if we have approval from @decause

**Comment by decause** [comment]
OK, deploy strategy confirmed and tested! Nice work everyone!
