### ISSUE TITLE
Introduce responsive data table ui library.

### ISSUE THREAD

**Issue by kahneraja** [DevProgress/csv-simple-search#3]
we need a client side js library that allows us to provide a searchable / sortable data tables approach.

**Comment by kahneraja** [comment]
exploring possible client side libraries that can take a cvs file and render it as a searching table. might also be able to export.

**Comment by kahneraja** [comment]
Aiming to use json to csv so that the resulting data table can export json to excel.

See #4

**Comment by kahneraja** [comment]
Data table considerations:
- mobile responsive (?! Tables and mobile is hard!)
- searching "anything".
- sorting (optional)

**Comment by arvind** [comment]
A basic data table was introduced with #7. Perhaps we want to break this up into separate issues for additional functionality?
