### ISSUE TITLE
Fix Strange Papaparse Error?

### ISSUE THREAD

**Issue by decause** [DevProgress/csv-simple-search#30]
Object { type: "FieldMismatch", code: "TooFewFields", message: "Too few fields: expected 8 fields b…", row: 4 }

![screenshot from 2016-08-09 22-32-06](https://cloud.githubusercontent.com/assets/427420/17540063/5974059c-5e81-11e6-9677-bc7dcc9d2197.png)

**Comment by decause** [comment]
I thought that perhaps this was related to not using quotechars in our .csv dialect, but I was incorrect. Other ideas?

**Comment by Cait** [comment]
Is there an extra line at the end of the file? I had that problem with the first sample file -- papaparse was trying to read the last empty line as a single "" field.
