### ISSUE TITLE
Consolidate CSS styling

### ISSUE THREAD

**Issue by Cait** [DevProgress/csv-simple-search#43]
It looks like we're loading two versions of normalize.css (v4.1.1 and v3.0.3 from Bootstrap). Also, there's styling in components/DataTable.css that should be reconciled with styles.css.

It would also be nice to minify/remove comments from the released version, but that's less important.

**Comment by brianlevy** [comment]
Also, I think we get rid of DataTable.css and use media queries to accomplish what it is doing.

**Comment by Cait** [comment]
We're doing it that way so that we can dynamically set the width breakpoints based on the number of columns in the csv file.

**Comment by samuelcole** [comment]
I would actually prefer to go the other way: move as much as we can out of `styles.css` into component specific stylesheets. The reason for that is tightly scoping the CSS to the component it styles, to reduce collisions in selectors, and making it easier to reason with individual components as the app grows.

That being said, this app might not grow much further, so it might be useful for people to see all the styles in one place?

**Comment by decause** [comment]
I'm +0 on either approach, and will defer to the folks here. Though this app has a particular use in mind, I think that "generic csv multisearch and export" tool can be useful beyond even HfA, potentially other campaigns too!

**Comment by decause** [comment]
@samuelcole @Cait 

Can we close this yet?
