### ISSUE TITLE
Search for multiple keywords

### ISSUE THREAD

**Issue by decause** [DevProgress/csv-simple-search#51]
The search works great for single words, but it would be even more useful if we could search on multiple words just by putting  a 'space' in between each. For example:

If I search for "NV" I get Lucky's Tasty Viddles.
If I search for "Viddles" I get Lucky's Tasty Viddles.
If I search for "NV Viddles" I get zero results.

I have updated the default.csv to include Multiple entries for "Flowers" in NV, so that we can test results by searching for "NV Flowers" and seeing if both "Lucky's" and "Deluxe" entries show up. :)

**Comment by kahneraja** [comment]
Will add this together today / tomoz.

**Comment by alexyaseen** [comment]
So this should be an AND search by default?

**Comment by decause** [comment]
@kahneraja yes, defaulting to an "AND" query should work

**Comment by samuelcole** [comment]
i'm going to start work on this right now, if no one else is already working on it
