### ISSUE TITLE
Moar HfA stylized look and feel?

### ISSUE THREAD

**Issue by decause** [DevProgress/csv-simple-search#67]
Though we cannot add an HfA logo onto the page, perhaps there are some ways we can improve the look/feel of this site?
- [x] Use the Sharp Unity Typeface?
- [x] Incorporate colors from the HfA palette?
- [x] other ideas?

**Comment by rschroed** [comment]
Here's the quick tweak I posted in slack. 
• Blue background in header ( #0057B8 )
• Swapped in Sharp Unity ExtraBold for the "DevProgress" word mark. 

![slice 1](https://cloud.githubusercontent.com/assets/12657/17911156/0d765d32-6941-11e6-88b1-ab2db9c0b064.png)

**Comment by decause** [comment]
@rschroed awesome!

I liked how there was some variation to our old word mark, so maybe we could try doing <code>bold</code> on "Dev" and <code>ExtraBold</code> on "Progress"?

@mattrothenberg thoughts?

**Comment by decause** [comment]
If there were a way to take advantage of the "even/odd" striped quality of the table, perhaps we could use a very subtle hint of an accent color in the table itself? Only if it is a trivial change though, because many datatable solutions come with that option out of the box?

Moar thoughts?

**Comment by rschroed** [comment]
yeah, if alt colors on the rows is easy, I'd recommend #f7f7f7 (or #efefef if that seems too light.)
![slice 1](https://cloud.githubusercontent.com/assets/12657/17916225/356bd518-6966-11e6-9a1c-e0a300fb2520.png)

Attached.

**Comment by rschroed** [comment]
re: the logo, I don't have 'bold' just semi and extra so I can't try it right now. Regardless, you'd probably want that as part of the SVG. Let me know if there's anything I can do to help with that.

**Comment by decause** [comment]
@rschroed have you sent a PR? I think we can merge what you've got so for :)

**Comment by rschroed** [comment]
ha, no. I don't have the code checked out or a build running. Let me spend a few minutes and see what I can do. Otherwise I'll copy some CSS from the inspector here for someone to apply.

**Comment by rschroed** [comment]
@decause I totally just sent a PR. And, FYI, I'm totally not a developer. I know just enough to be dangerous to us both. Let me know if you have any questions, and please test this!

**Comment by jillh510** [comment]
Can this issue be closed?

**Comment by decause** [comment]
@jillh510 yep!
