### ISSUE TITLE
make links clickable

### ISSUE THREAD

**Issue by decause** [DevProgress/csv-simple-search#72]
There are libraries (even react libraries) that help with this.

**Comment by decause** [comment]
http://tasti.github.io/react-linkify/

Via @dxa4481

**Comment by dxa4481** [comment]
This is a potential XSS vector, so library++ 

``` html
<a href="javascript:alert(1)"></a>
```

**Comment by bscofield** [comment]
On it.

**Comment by bscofield** [comment]
https://github.com/DevProgress/csv-simple-search/pull/73

**Comment by bscofield** [comment]
react-linkify uses markdown-it/linkify-it behind the scenes; some quick XSS testing later, it looks like it'll be OK (but more people banging on it on the security side is always a good idea)
